### ISSUE TITLE
empty @value and @examples fields

### ISSUE THREAD

**Issue by GregorDeCillia** [statistikat/surveysd#1]
I can't build the documentation since `@value` and `@examples` require values but are empty in `R/plot.R` and `R/bootstrap_mustistage.R`. Also, the `usage` section in `bootstrap.Rd` reads `rescaled.boot(...)` but should be `bootstrap(...)`.

**Comment by JohannesGuss** [comment]
documentation is fixed and function Name `bootstrap()` was changed to `rescaled.bootstrap()` to emphasize that this does not run a naive bootstrap procedure.
