### ISSUE TITLE
ipf: Numerical constraints with missings cause unexpected behavior

### ISSUE THREAD

**Issue by GregorDeCillia** [statistikat/surveysd#24]
If numerical constraints are used in `ipf`, missings (`NA`s) lead to problems because certains sums cannot be calculated in a proper manner. See the example above where the marginal distribution (`conP_1`) of the calibrated dataset is widely different from the original one (`conP`) with relative errors of `99.8%`

Thanks @froehmar for reporting this!

```r
library(surveysd)

## load data and construct constraint
eusilc <- demo.eusilc(n = 1, prettyNames = TRUE)
conP <- xtabs(pWeight * eqIncome ~ gender, data = eusilc)

## add NAs
setNA <- eusilc[, sample(hid, 1), by = .(hsize, region)]
eusilc[.(hid = setNA$V1), eqIncome := NA, on = .(hid)]

## calibrate
calibweights2 <- ipf(
  eusilc,
  conP = list(eqIncome = conP),
  bound = NULL,
  verbose = TRUE
)
#> Convergence reached in 1 steps

## compare
(conP_1 <- xtabs(calibWeight*eqIncome ~ gender, data = calibweights2))
#> gender
#>      male    female 
#> 148110451 143486057
(conP_1 - conP) / conP
#> gender
#>       male     female 
#> -0.9982024 -0.9982144
```

**TODO**: Add a new input check, that throws an error if missings are contained in `conP` or `conH`

**Comment by JohannesGuss** [comment]
Added checks for `conP`, `conH` and `w`, which trigger errors wenn `NA`s are found.
Included this behaviour into the unit testing
