### ISSUE TITLE
CRAN 1.3.0 release

### ISSUE THREAD

**Issue by alexkowa** [statistikat/surveysd#30]
Is the right time for a new CRAN release or if not what to fix before? @JohannesGuss and @GregorDeCillia

**Comment by GregorDeCillia** [comment]
I think a new release should be fine unless we want to tackle #25 before that. What do you think @JohannesGuss ?

**Comment by JohannesGuss** [comment]
@GregorDeCillia, @alexkowa, I think we can release a new version right away and leave the open issues to the next minor version change...

**Comment by alexkowa** [comment]
@GregorDeCillia is looking at an issue of ipf with looseH=TRUE that. After that is fixed (end of the week or next week ?) we should really publish the new version
