### ISSUE TITLE
Changing default values (Breaking changes)

### ISSUE THREAD

**Issue by GregorDeCillia** [statistikat/surveysd#4]
When rewriting documentation for this package, I found that I use `period_mean = NULL` in `calc.stError` for the most part and I think that should be the default going forward. It also makes sense from a conceptual POV since not every dataset has three or more reference periods and the output for `period_mean = NULL` is much "cleaner". However, this would be an API **breaking** change

Other default arguments, I'd like to change are far less critical.

* [x] `period_mean = NULL`: the critical one
* [x] `hid = NULL`: If no household variable is provided, use clustering accoridng to the `cluster` argument.  (**Not breaking**, since there is currently no default value)
* [x] `strata = NULL`: If no strata is provided, use no stratification. (**Breaking**, but the current default value is a hard-coded variable name from EU-SILC that needs to go anyways)
* [x] `period = NULL`: If no reference period is provided, assume all observations belong to the same period (**Not breaking**, since there is currently no default value)

What do you think @JohannesGuss ? If you are alright with those changes, I will start working on a branch to change the default arguments. Certain users will have to be notified prior to merging

**Comment by JohannesGuss** [comment]
Sounds good!

+ hid=NULL: clustering should still be possible of this is NULL. Only the final cluster stage will be the rowindex of each data record

Thanks!

**Comment by GregorDeCillia** [comment]
OK, I updated the TODO list accordingly
