### ISSUE TITLE
move ipu2 to surveysd?

### ISSUE THREAD

**Issue by alexkowa** [statistikat/surveysd#6]
@JohannesGuss @GregorDeCillia Should we move the function ipu2 to surveysd (and maybe rename it in the process) and only leave a small wrapper in simPop for backwards compatibility?

**Comment by GregorDeCillia** [comment]
I quite like the idea of moving the functionality of ipu2 to this package. However, surveysd is not on CRAN and simPop is. I am pretty sure CRAN would not allow surveysd to be in the Imports field of simPop for that reason.

 Therefore, I would suggest to also introduce a CRAN release in the process.

- [x] 1. copy (not move) ipu2 from simPop to this package. Maybe do some renaming and refactoring
- [x] 2. Release surveysd on CRAN
- [x] 3. replace the `simPop::ipu2` with a wrapper that uses `surveysd::ipu2`

**Comment by alexkowa** [comment]
As soon as surveysd is online on CRAN, we can push simPop, all the necessary changes are already on github

**Comment by GregorDeCillia** [comment]
Yes, but we should also revert https://github.com/statistikat/simPop/commit/53122197f4681fad64e11097cbfaf4ac6262d88d before submitting simPop to CRAN
