### ISSUE TITLE
ipf failes when a variable w is present...

### ISSUE THREAD

**Issue by alexkowa** [statistikat/surveysd#7]
ipu2 should at least give a useful errormessage in this case (or better avoid this issues)

**Comment by GregorDeCillia** [comment]
Repex (tested with the CRAN version of simPop from 2018-05-29):

```
library(simPop)

data(eusilcS)
setDT(eusilcS)
setnames(eusilcS, "rb050", "weight")
conP <- xtabs(weight*netIncome ~ rb090, data = eusilcS)

ipu2(eusilcS, conP = list(conP), w = "weight") 
eusilcS[, w := NA]
ipu2(eusilcS, conP = list(conP), w = "weight") 
#> Error in ipu_step_f(dat$calibWeight, combined_factors, conP[[i]]) : 
#>   Not compatible with requested type: [type=list; target=double].
```

**Comment by GregorDeCillia** [comment]
Now that ipf was migrated to the surveysd package, it could make sense to use `dt.eval` for more efficiency and also to resolve this issue.

@JohannesGuss Do you see an easy way to get rid of the `_safekeeping` logic in `R/ipf.R` by using `dt.eval` instead? Do you think it could make a performance difference?

**Comment by alexkowa** [comment]
I started to work on it in branch ipf_dt_get
